CREATE TABLE users(
  id IDENTITY,
  email VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  password VARCHAR(255)NOT NULL,
  role VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

